- name: logstash repo
  ansible.builtin.template:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo

- name: Installing logstash
  ansible.builtin.dnf:
    name: logstash
    state: present

- name:  logstash configuration
  ansible.builtin.template:
    src: logstash-sample.conf
    dest: /etc/logstash/logstash-sample.conf

- name: Start Logstash
  ansible.builtin.systemd:
    name: logstash
    state: started
    enabled: yes
