- name: setup prometheus repo
  ansible.builtin.template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: setup prometheus
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service